(() => {
'use strict';
const GRID=24;
const COLORS=['#111827','#ffffff','#ff4d6d','#ff8c42','#ffd166','#63e06f','#42d6c7','#3aa7ff','#5865f2','#9b5de5','#f15bb5','#8b5e3c'];
const ATTR={fire:'炎',water:'水',nature:'草',bolt:'雷',dark:'闇',light:'光',neutral:'無'};
const ADV={fire:'nature',nature:'water',water:'fire',bolt:'water',dark:'light',light:'dark'};
const PRE=['ネオ','ギガ','クロノ','ヴォイド','ルミナ','グリム','ゼータ','アストラ','ボルト','マグナ','ミラ','ゼノ','アーク','メガ','ナノ'];
const SUF=['レックス','モール','ビット','ファング','ノヴァ','ギア','ゴン','リーパー','バード','スライム','コア','ナイト','ドレイク','ウォーカー','ゼロ'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const state={screen:'title',grid:blank(),color:COLORS[0],tool:'pen',undo:[],enemy:null,last:null,stage:1,profile:load('pf2_profile',{name:'PLAYER',rating:1200,wins:0,losses:0,streak:0,xp:0,level:1,coins:0,bestTower:0}),collection:load('pf2_collection',[]),ach:load('pf2_ach',{}),settings:load('pf2_settings',{speed:2,vibration:true,motion:true}),mode:'normal',prompt:null,team:[],peer:null,conn:null,isHost:false,room:null,remote:null,ready:false,lastReplay:null};
function save(){localStorage.setItem('pf2_profile',JSON.stringify(state.profile));localStorage.setItem('pf2_collection',JSON.stringify(state.collection.slice(-80)));localStorage.setItem('pf2_ach',JSON.stringify(state.ach));localStorage.setItem('pf2_settings',JSON.stringify(state.settings))}
function blank(){return Array.from({length:GRID},()=>Array(GRID).fill(null))}
function clone(g){return g.map(r=>r.slice())}
function hash(s){let h=2166136261>>>0;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=typeof seed==='number'?seed:hash(seed);return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function pick(r,a){return a[Math.floor(r()*a.length)]}
function buzz(ms=25){if(state.settings.vibration&&navigator.vibrate)navigator.vibrate(ms)}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function init(){renderShell();bindNav();buildPalette();bindDraw();bindCore();state.enemy=genEnemy('boot-'+Date.now(),0);renderEnemy();renderProfile();renderCollection();renderRanking();renderAchievements();titleSprites();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}
function renderShell(){document.body.innerHTML=`<div class="scanlines"></div><header class="topbar"><button id="homeBtn" class="icon-btn">◆</button><div class="brand-mini">PIXEL FORGE <b>ARENA // V2</b></div><div class="player-chip"><span id="playerNameTop">PLAYER</span><b id="ratingTop">1200</b><i id="levelTop">LV1</i></div></header><main>
<section id="screen-title" class="screen active title-screen"><div class="hero-grid"></div><div class="title-wrap"><div class="eyebrow">PROCEDURAL MONSTER ENGINE / NO GENERATIVE AI API</div><h1>PIXEL<br><span>FORGE</span><br>ARENA</h1><p class="tagline">描く。解析する。育てる。戦わせる。</p><div class="title-monsters"><canvas id="titleA" width="120" height="120"></canvas><div class="vs-burst">VS</div><canvas id="titleB" width="120" height="120"></canvas></div><div class="profile-row"><input id="nameInput" maxlength="12" placeholder="PLAYER NAME"><button id="saveName" class="small-btn">保存</button></div><div class="menu-grid">${menu('battle','01','通常バトル','DRAW & FIGHT','primary')}${menu('post','02','後付けバトル','PROMPT DRAW')}${menu('tower','03','無限タワー','ENDLESS')}${menu('team','04','6体チーム戦','TEAM BATTLE')}${menu('online','05','ネット対戦','P2P ROOM')}${menu('collection','06','図鑑・育成','ARCHIVE')}${menu('tournament','07','トーナメント','8 MONSTER CUP')}${menu('code','08','モンスターコード','EXPORT / IMPORT')}${menu('daily','09','デイリーチャレンジ','DAILY SEED')}${menu('sim','10','AIシミュレーター','100 BATTLES')}${menu('ranking','11','ランキング','LOCAL RATING')}${menu('achievements','12','実績','ACHIEVEMENTS')}${menu('lab','13','AIラボ','ENGINE INSPECTOR')}${menu('settings','14','設定','MOBILE / EFFECTS')}</div></div><footer class="title-footer">V2.0 · MOBILE FIRST · ORIGINAL PROCEDURAL ASSETS</footer></section>
${battleScreen('battle','通常バトル','SOLO MODE')}${battleScreen('post','後付けバトル','PROMPT MODE',true)}
<section id="screen-tower" class="screen"><div class="section-head"><div><small>ENDLESS</small><h2>無限タワー</h2></div><div class="stage-chip">BEST <b id="towerBest">0</b>F</div></div><div class="card mode-card"><p>1体のモンスターで階層を登る。5階ごとにボス。</p><button id="towerStart" class="cta-btn wide">タワー開始</button><div id="towerStatus" class="mode-output"></div></div></section>
<section id="screen-team" class="screen"><div class="section-head"><div><small>6v6</small><h2>6体チームバトル</h2></div><button id="teamAuto" class="small-btn">自動編成</button></div><div class="card"><div id="teamSlots" class="team-slots"></div><button id="teamBattle" class="cta-btn wide">敵チームと戦う</button><div id="teamResult" class="mode-output"></div></div></section>
<section id="screen-online" class="screen"><div class="section-head"><div><small>ONLINE PVP</small><h2>ネット対戦</h2></div><div id="netLamp" class="net-lamp">OFFLINE</div></div><div class="online-grid"><article class="card"><h3>HOST</h3><button id="createRoom" class="cta-btn wide">ルーム作成</button><div id="roomBox" class="room-box hidden"><small>ROOM CODE</small><strong id="roomCode">------</strong></div></article><article class="card"><h3>JOIN</h3><input id="joinCode" maxlength="6" class="room-input" placeholder="ABC123"><button id="joinRoom" class="cta-btn wide">参加</button></article></div><div id="onlineCard" class="card hidden"><div class="match-versus"><div><b id="onlineMe">YOU</b><small id="onlineMeState">WAIT</small></div><div class="vs-burst">VS</div><div><b id="onlineRival">RIVAL</b><small id="onlineRivalState">WAIT</small></div></div><button id="sendReady" class="cta-btn wide">モンスター送信・準備完了</button><div id="onlineResult" class="mode-output"></div></div></section>
<section id="screen-collection" class="screen"><div class="section-head"><div><small>ARCHIVE + TRAINING</small><h2>モンスター図鑑・育成</h2></div><div class="stage-chip"><b id="collectionCount">0</b>/80</div></div><div id="collectionGrid" class="collection-grid"></div></section>
<section id="screen-tournament" class="screen"><div class="section-head"><div><small>CUP MODE</small><h2>トーナメント</h2></div><button id="tournamentStart" class="small-btn">新規開催</button></div><div class="card"><div id="bracket" class="bracket"></div></div></section>
<section id="screen-code" class="screen"><div class="section-head"><div><small>MONSTER CODE</small><h2>召喚コード</h2></div></div><div class="online-grid"><div class="card"><h3>最後のモンスターを書き出す</h3><textarea id="exportCode" class="codebox" readonly></textarea><button id="makeCode" class="cta-btn wide">コード生成</button></div><div class="card"><h3>コードから召喚</h3><textarea id="importCode" class="codebox" placeholder="PFA2-..."></textarea><button id="loadCode" class="cta-btn wide">召喚する</button></div></div></section>
<section id="screen-daily" class="screen"><div class="section-head"><div><small>DAILY</small><h2>デイリーチャレンジ</h2></div><div class="stage-chip" id="dailyDate"></div></div><div class="card mode-card"><canvas id="dailyEnemy" width="240" height="240" class="sprite-canvas"></canvas><h3 id="dailyName">---</h3><p>全プレイヤーで同じ日付シードの敵。</p><button id="dailyFight" class="cta-btn wide">挑戦する</button><div id="dailyResult" class="mode-output"></div></div></section>
<section id="screen-sim" class="screen"><div class="section-head"><div><small>AI LAB</small><h2>100戦シミュレーター</h2></div></div><div class="card mode-card"><p>最後のモンスター vs 現在の敵を100シードで高速対戦。</p><button id="runSim" class="cta-btn wide">100戦解析</button><div id="simResult" class="mode-output"></div></div></section>
<section id="screen-ranking" class="screen"><div class="section-head"><div><small>RATING BOARD</small><h2>ランキング</h2></div><div class="stage-chip">LOCAL</div></div><div class="card"><div id="rankingList" class="ranking-list"></div></div></section>
<section id="screen-achievements" class="screen"><div class="section-head"><div><small>ACHIEVEMENTS</small><h2>実績</h2></div></div><div id="achievementGrid" class="achievement-grid"></div></section>
<section id="screen-lab" class="screen"><div class="section-head"><div><small>ENGINE INSPECTOR</small><h2>自作AIラボ</h2></div><div class="net-lamp good">API 0</div></div><div class="lab-grid">${labCards()}</div></section>
<section id="screen-settings" class="screen"><div class="section-head"><div><small>SETTINGS</small><h2>設定</h2></div></div><div class="card settings-card"><label>戦闘速度<select id="speedSel"><option value="1">ゆっくり</option><option value="2">標準</option><option value="4">高速</option><option value="20">瞬間</option></select></label><label><input type="checkbox" id="vibSet"> バイブレーション</label><label><input type="checkbox" id="motionSet"> 戦闘アニメーション</label><button id="resetData" class="ghost-btn danger">全セーブデータ削除</button></div></section>
</main><div id="battleModal" class="modal hidden"><div class="modal-card"><button id="modalX" class="modal-x">×</button><div class="battle-stage"><div class="fighter"><canvas id="pCanvas" width="192" height="192"></canvas><b id="pName">YOU</b><div class="hp"><i id="pHp"></i></div><small id="pHpText"></small></div><div class="battle-center"><div class="vs-burst big">VS</div><div id="turnLabel">ANALYZING</div></div><div class="fighter"><canvas id="eCanvas" width="192" height="192"></canvas><b id="eName">ENEMY</b><div class="hp"><i id="eHp"></i></div><small id="eHpText"></small></div></div><div id="reasonPanel" class="reason-panel"></div><div id="battleLog" class="battle-log"></div><div id="battleResult" class="battle-result-box"></div><button id="nextBattle" class="cta-btn wide hidden">次へ</button></div></div><div id="toast" class="toast"></div>`}
function menu(go,n,t,s,c=''){return`<button data-go="${go}" class="menu-btn ${c}"><span>${n}</span><b>${t}</b><small>${s}</small></button>`}
function battleScreen(id,title,small,prompt=false){return`<section id="screen-${id}" class="screen"><div class="section-head"><div><small>${small}</small><h2>${title}</h2></div><div class="stage-chip">STAGE <b id="${id}Stage">01</b></div></div>${prompt?`<div class="card prompt-card"><b>今回のお題：</b><span id="promptText">---</span><canvas id="promptCanvas" width="144" height="144"></canvas><button id="newPrompt" class="small-btn">お題変更</button></div>`:''}<div class="battle-layout"><article class="enemy-panel card"><div class="card-head"><span>ENEMY / PROCEDURAL</span><b id="${id}Threat">THREAT C</b></div><canvas id="${id}Enemy" width="288" height="288" class="sprite-canvas"></canvas><h3 id="${id}EnemyName">---</h3><p id="${id}EnemyTrait" class="muted"></p><div id="${id}EnemyStats" class="stats"></div><button data-reroll="${id}" class="ghost-btn">敵を再生成</button></article><article class="draw-panel card"><div class="card-head"><span>YOUR MONSTER / 24×24</span><b class="inkMeter">INK 0%</b></div><div class="canvas-wrap"><canvas id="${id}Draw" class="draw-canvas" width="480" height="480"></canvas><div class="draw-hint">指で描く</div></div><div class="palette"></div><div class="tool-row"><button data-tool="pen" class="tool active">ペン</button><button data-tool="erase" class="tool">消す</button><button data-tool="fill" class="tool">塗る</button><button class="tool undoBtn">戻す</button><button class="tool danger clearBtn">全消し</button></div><div class="action-row"><button class="ghost-btn randomDraw">自動下書き</button><button data-fight="${id}" class="cta-btn">解析して戦う</button></div></article></div></section>`}
function labCards(){return[['PIXEL VISION','密度・輪郭・対称性・重心・色・連結・突起を抽出。'],['STAT SYNTHESIS','特徴量から能力・属性・クラス・スキルを非線形合成。'],['TACTICAL BRAIN','HP・相性・速度差・防御差・状態異常から行動を評価。'],['STATUS ENGINE','炎上・毒・スタン・バリア・回復を処理。'],['ENEMY GENOME','骨格・角・翼・尾・装甲・顔・属性パレットをシード合成。'],['ADAPTIVE DIFFICULTY','連勝・レート・階層から敵補正を強化。'],['TEAM AI','6体の属性と勝敗から交代戦を処理。'],['SIMULATOR','複数シードを反復し勝率と平均ターンを推定。']].map((x,i)=>`<article class="card"><h3>${String(i+1).padStart(2,'0')} / ${x[0]}</h3><p>${x[1]}</p></article>`).join('')}
function bindNav(){$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#homeBtn').onclick=()=>go('title');$('#nameInput').value=state.profile.name;$('#saveName').onclick=()=>{state.profile.name=($('#nameInput').value.trim()||'PLAYER').slice(0,12);save();renderProfile();toast('名前を保存')}}
function go(n){$$('.screen').forEach(x=>x.classList.remove('active'));$('#screen-'+n)?.classList.add('active');state.screen=n;scrollTo(0,0);if(n==='collection')renderCollection();if(n==='ranking')renderRanking();if(n==='achievements')renderAchievements();if(n==='daily')renderDaily();if(n==='team')renderTeam()}
function renderProfile(){$('#playerNameTop').textContent=state.profile.name;$('#ratingTop').textContent=state.profile.rating;$('#levelTop').textContent='LV'+state.profile.level;$('#towerBest').textContent=state.profile.bestTower}
function buildPalette(){$$('.palette').forEach(p=>{p.innerHTML='';COLORS.forEach((c,i)=>{const b=document.createElement('button');b.className='swatch'+(i===0?' active':'');b.style.background=c;b.onclick=()=>{state.color=c;$$('.swatch').forEach(s=>s.classList.toggle('active',s===b));state.tool='pen';syncTools()};p.appendChild(b)})})}
function bindDraw(){$$('.draw-canvas').forEach(c=>{let drawing=false,last=null;const pos=e=>{const r=c.getBoundingClientRect();return{x:clamp(Math.floor((e.clientX-r.left)/r.width*GRID),0,23),y:clamp(Math.floor((e.clientY-r.top)/r.height*GRID),0,23)}};c.addEventListener('pointerdown',e=>{e.preventDefault();c.setPointerCapture(e.pointerId);drawing=true;pushUndo();const p=pos(e);apply(p.x,p.y);last=p});c.addEventListener('pointermove',e=>{if(!drawing||state.tool==='fill')return;const p=pos(e);line(last,p,(x,y)=>apply(x,y,false));last=p});c.addEventListener('pointerup',()=>drawing=false);c.addEventListener('pointercancel',()=>drawing=false)});$$('[data-tool]').forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;syncTools()});$$('.undoBtn').forEach(b=>b.onclick=()=>{if(state.undo.length){state.grid=state.undo.pop();renderAllDraw()}});$$('.clearBtn').forEach(b=>b.onclick=()=>{pushUndo();state.grid=blank();renderAllDraw()});$$('.randomDraw').forEach(b=>b.onclick=()=>{pushUndo();state.grid=genSprite('draft-'+Date.now(),.3).grid;renderAllDraw()});renderAllDraw()}
function syncTools(){$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===state.tool))}
function pushUndo(){state.undo.push(clone(state.grid));if(state.undo.length>30)state.undo.shift()}
function apply(x,y,render=true){if(state.tool==='fill')flood(x,y,state.color);else state.grid[y][x]=state.tool==='erase'?null:state.color;if(render)renderAllDraw()}
function flood(x,y,c){const old=state.grid[y][x];if(old===c)return;const q=[[x,y]],seen=new Set;while(q.length){const [a,b]=q.pop(),k=a+','+b;if(a<0||b<0||a>=24||b>=24||seen.has(k)||state.grid[b][a]!==old)continue;seen.add(k);state.grid[b][a]=c;q.push([a+1,b],[a-1,b],[a,b+1],[a,b-1])}renderAllDraw()}
function line(a,b,fn){let x0=a.x,y0=a.y,x1=b.x,y1=b.y,dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,er=dx+dy;while(true){fn(x0,y0);if(x0===x1&&y0===y1)break;const e2=2*er;if(e2>=dy){er+=dy;x0+=sx}if(e2<=dx){er+=dx;y0+=sy}}renderAllDraw()}
function renderGrid(c,g,bg='#0f1622',grid=false){if(!c)return;const x=c.getContext('2d'),w=c.width/24,h=c.height/24;x.imageSmoothingEnabled=false;x.fillStyle=bg;x.fillRect(0,0,c.width,c.height);for(let y=0;y<24;y++)for(let i=0;i<24;i++)if(g[y][i]){x.fillStyle=g[y][i];x.fillRect(i*w,y*h,Math.ceil(w),Math.ceil(h))}if(grid){x.strokeStyle='rgba(20,30,45,.08)';for(let i=0;i<=24;i++){x.beginPath();x.moveTo(i*w,0);x.lineTo(i*w,c.height);x.stroke();x.beginPath();x.moveTo(0,i*h);x.lineTo(c.width,i*h);x.stroke()}}}
function renderAllDraw(){$$('.draw-canvas').forEach(c=>renderGrid(c,state.grid,'#f4f6ee',true));const n=state.grid.flat().filter(Boolean).length;$$('.inkMeter').forEach(e=>e.textContent='INK '+Math.round(n/576*100)+'%');$$('.draw-hint').forEach(e=>e.classList.toggle('hidden',n>0))}
function analyze(g,boost=0){const f=[],colors={};for(let y=0;y<24;y++)for(let x=0;x<24;x++)if(g[y][x]){f.push([x,y,g[y][x]]);colors[g[y][x]]=(colors[g[y][x]]||0)+1}const n=f.length;if(!n)return null;let per=0,sp=0,edge=0,sx=0,sy=0,top=0,left=0;for(const [x,y]of f){sx+=x;sy+=y;if(y<12)top++;if(x<12)left++;if(x===0||y===0||x===23||y===23)edge++;let nei=0;for(const[d,e]of[[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+d,yy=y+e;if(xx>=0&&yy>=0&&xx<24&&yy<24&&g[yy][xx])nei++;else per++}if(nei<=1)sp++}let sym=0;for(let y=0;y<24;y++)for(let x=0;x<12;x++)if(Boolean(g[y][x])===Boolean(g[y][23-x]))sym++;sym/=288;const comps=components(g),density=n/576,dom=Object.entries(colors).sort((a,b)=>b[1]-a[1])[0][0],attr=colorAttr(dom),raw={density,perimeter:per/(n*4),symmetry:sym,components:comps,spikes:sp/n,edge:edge/n,cx:sx/n/23,cy:sy/n/23,vertical:top/(n-top+1),lateral:Math.abs(left-(n-left))/n,colorCount:Object.keys(colors).length};const stats={atk:score(22+density*45+raw.spikes*68+raw.perimeter*22+raw.colorCount*2+boost),def:score(20+density*58+sym*24-raw.spikes*14+boost),spd:score(25+(1-density)*31+raw.spikes*33+(1-raw.edge)*12-raw.lateral*12+boost),mag:score(18+raw.colorCount*7+(attr==='neutral'?0:15)+Math.abs(.5-raw.cy)*22+boost),vit:score(28+density*50+Math.min(n/15,26)+sym*10+boost)};const archetype=classify(stats),skills=skillsFor(stats,raw,attr),power=Math.round((stats.atk*1.15+stats.def+stats.spd+stats.mag+stats.vit*1.1)/5);return{stats,raw,attr,archetype,skills,power,dominant:dom}}
function score(v){return clamp(Math.round(v),8,99)}
function components(g){const seen=new Set;let c=0;for(let y=0;y<24;y++)for(let x=0;x<24;x++){if(!g[y][x]||seen.has(x+','+y))continue;c++;const q=[[x,y]];while(q.length){const[a,b]=q.pop(),k=a+','+b;if(a<0||b<0||a>=24||b>=24||seen.has(k)||!g[b][a])continue;seen.add(k);q.push([a+1,b],[a-1,b],[a,b+1],[a,b-1])}}return c}
function colorAttr(c){if(['#ff4d6d','#ff8c42'].includes(c))return'fire';if(['#3aa7ff','#5865f2','#42d6c7'].includes(c))return'water';if(c==='#63e06f')return'nature';if(c==='#ffd166')return'bolt';if(['#9b5de5','#f15bb5','#111827'].includes(c))return'dark';if(c==='#ffffff')return'light';return'neutral'}
function classify(s){return[['ブレイカー',s.atk],['ガーディアン',s.def+s.vit*.3],['スカウト',s.spd],['アルカナ',s.mag],['ビースト',(s.atk+s.vit)/2],['トリックスター',(s.spd+s.mag)/2]].sort((a,b)=>b[1]-a[1])[0][0]}
function skillsFor(s,r,a){const o=[];if(s.atk>66||r.spikes>.06)o.push({name:'スパイクラッシュ',kind:'attack',scale:1.42,status:a==='fire'?'burn':null});if(s.def>69||r.symmetry>.78)o.push({name:'フォートレス',kind:'guard',scale:1.7,status:'barrier'});if(s.spd>70)o.push({name:'フェイズステップ',kind:'speed',scale:1.26,status:'stun'});if(s.mag>64)o.push({name:ATTR[a]+'エーテル',kind:'magic',scale:1.46,status:a==='nature'?'poison':a==='bolt'?'stun':null});if(s.vit>72)o.push({name:'リペアコア',kind:'heal',scale:1,status:'heal'});if(r.components>2)o.push({name:'マルチコア',kind:'multi',scale:1.25,status:null});if(!o.length)o.push({name:'コアバースト',kind:'attack',scale:1.25,status:null});return o.slice(0,3)}
function nameFor(seed,a){const r=rng(seed);return(a&&a!=='neutral'?ATTR[a]:'')+pick(r,PRE)+pick(r,SUF)}
function trait(m){return`${m.archetype}型 / ${ATTR[m.attr]}属性 / POWER ${m.power} / ${m.skills.map(x=>x.name).join('・')}`}
function genSprite(seed,bias=0,boss=false){const r=rng(seed),g=blank(),type=Math.floor(r()*9),c1=pick(r,COLORS.slice(2)),c2=pick(r,COLORS.slice(1));const set=(x,y,c=c1)=>{x=Math.round(x);y=Math.round(y);if(x>0&&y>0&&x<23&&y<23)g[y][x]=c};const cx=11.5;if(type%3===0){for(let y=5;y<21;y++)for(let x=3;x<21;x++){const dx=(x-cx)/7,dy=(y-14)/6;if(dx*dx+dy*dy<1+r()*.18)set(x,y)}}else if(type%3===1){for(let y=4;y<21;y++){const h=Math.round(3+Math.sin((y-4)/17*Math.PI)*6);for(let x=Math.round(cx-h);x<=Math.round(cx+h);x++)if(r()>.12)set(x,y)}}else{for(let y=7;y<20;y++)for(let x=6;x<18;x++)if((x+y+type)%6!==0)set(x,y);for(let i=0;i<6;i++){set(5-i,8+i%3);set(18+i,8+i%3)}}for(let y=0;y<24;y++)for(let x=0;x<12;x++)if(g[y][x]&&r()>.13)g[y][23-x]=g[y][x];for(let i=0;i<8+bias*20+(boss?22:0);i++)set(2+Math.floor(r()*20),2+Math.floor(r()*20),r()>.7?c2:c1);set(9,10,'#ffffff');set(14,10,'#ffffff');if(boss){for(let x=6;x<18;x++){set(x,3,c2);if(x%2)set(x,2,c2)}for(let y=9;y<17;y++){set(2,y,c2);set(21,y,c2)}}return{grid:g,seed,type,c1,c2,boss}}
function genEnemy(seed,diff=0,boss=false){const spr=genSprite(seed,diff,boss),a=analyze(spr.grid,clamp(diff*6+(boss?10:0),0,25)),name=nameFor(seed,a.attr)+(boss?' Ω':'');return{...spr,...a,name,trait:trait({...a,name}),level:1,xp:0}}
function renderEnemy(){for(const id of['battle','post']){renderGrid($('#'+id+'Enemy'),state.enemy.grid);$('#'+id+'EnemyName').textContent=state.enemy.name;$('#'+id+'EnemyTrait').textContent=state.enemy.trait;$('#'+id+'Threat').textContent='THREAT '+['C','B','A','S','Ω'][clamp(Math.floor((state.enemy.power-35)/13),0,4)];renderStats($('#'+id+'EnemyStats'),state.enemy.stats);$('#'+id+'Stage').textContent=String(state.stage).padStart(2,'0')}}
function renderStats(el,s){if(el)el.innerHTML=['atk','def','spd','mag','vit'].map(k=>`<div class="stat"><small>${k.toUpperCase()}</small><b>${s[k]}</b></div>`).join('')}
function bindCore(){$$('[data-reroll]').forEach(b=>b.onclick=()=>{state.enemy=genEnemy('reroll-'+Date.now(),state.stage/7);renderEnemy()});$$('[data-fight]').forEach(b=>b.onclick=()=>fightFromDraw(b.dataset.fight));$('#modalX').onclick=()=>$('#battleModal').classList.add('hidden');$('#nextBattle').onclick=()=>{$('#battleModal').classList.add('hidden');state.stage++;state.enemy=genEnemy('stage-'+state.stage+'-'+Date.now(),state.stage/7,state.stage%5===0);renderEnemy()};$('#newPrompt').onclick=newPrompt;newPrompt();bindModes();bindOnline();bindSettings()}
function newPrompt(){const r=rng('prompt-'+Date.now()),shapes=['左右対称の核','上に大きな角','3つの浮遊コア','長い尾','大きな盾','左右に翼','細長い高速型','丸い重装甲'];state.prompt={text:pick(r,shapes),grid:genSprite('prompt-shape-'+Date.now(),.1).grid};$('#promptText').textContent=state.prompt.text;renderGrid($('#promptCanvas'),state.prompt.grid,'#0f1622')}
function fightFromDraw(mode){const a=analyze(state.grid);if(!a){toast('まず描いてください');return}let bonus=0;if(mode==='post'&&state.prompt){const target=analyze(state.prompt.grid);bonus=Math.round((1-Math.abs(a.raw.symmetry-target.raw.symmetry))*5)}const name=nameFor(JSON.stringify(a.raw)+Date.now(),a.attr),m={grid:clone(state.grid),...a,name,trait:trait({...a,name}),level:1,xp:0,id:'m'+Date.now()};if(bonus){for(const k in m.stats)m.stats[k]=clamp(m.stats[k]+bonus,8,99);m.power+=bonus}state.last=m;addMonster(m);showBattle(m,state.enemy,{rated:true})}
function signature(g){return hash(g.flat().map(x=>x||'.').join('')).toString(36)}
function addMonster(m){if(!state.collection.some(x=>signature(x.grid)===signature(m.grid))){state.collection.push(pack(m));unlock('collector');save()}}
function pack(m){return{id:m.id||'m'+Date.now(),name:m.name,grid:m.grid,stats:m.stats,raw:m.raw,attr:m.attr,archetype:m.archetype,skills:m.skills,power:m.power,trait:m.trait,level:m.level||1,xp:m.xp||0,wins:m.wins||0,createdAt:m.createdAt||Date.now()}}
function revive(m){return{...m,trait:m.trait||trait(m),skills:m.skills||[]}}
function fighter(m){const lvl=1+(m.level||1)*.015;return{m,s:Object.fromEntries(Object.entries(m.stats).map(([k,v])=>[k,Math.round(v*lvl)])),hp:Math.round((110+m.stats.vit*2.3)*lvl),max:Math.round((110+m.stats.vit*2.3)*lvl),guard:0,cool:0,status:{burn:0,poison:0,stun:0,barrier:0}}}
function decide(a,b,r){const hp=a.hp/a.max,skill=a.cool<=0?24:0,heal=a.m.skills.some(x=>x.kind==='heal')&&hp<.42?38:0,guard=(hp<.3?28:6)+(b.s.atk>a.s.def?8:0),attack=24+(a.s.atk>b.s.def?8:0),tactical=skill+(a.s.mag>65?7:0),sum=attack+guard+tactical+heal,x=r()*sum;if(x<heal)return'heal';if(x<heal+guard)return'guard';if(x<heal+guard+tactical)return'skill';return'attack'}
function attrFactor(a,b){if(ADV[a]===b)return 1.2;if(ADV[b]===a)return .82;return 1}
function simulate(p,e,seed){const r=rng(seed),A=fighter(p),B=fighter(e),events=[];let turn=0;while(A.hp>0&&B.hp>0&&turn<24){turn++;tick(A,'p',events,turn,A,B);tick(B,'e',events,turn,A,B);if(A.hp<=0||B.hp<=0)break;const order=A.s.spd===B.s.spd?(r()>.5?[A,B]:[B,A]):A.s.spd>B.s.spd?[A,B]:[B,A];for(const a of order){const b=a===A?B:A,side=a===A?'p':'e';if(a.hp<=0||b.hp<=0)continue;if(a.status.stun>0){a.status.stun--;events.push(event(turn,`${a.m.name} はスタンして動けない！`,A,B));continue}const act=decide(a,b,r);resolve(a,b,act,r,turn,events,A,B,side)}}if(A.hp>0&&B.hp>0){A.hp-=Math.round(B.s.atk*.4);B.hp-=Math.round(A.s.atk*.4)}const winner=A.hp===B.hp?(A.m.power>=B.m.power?'p':'e'):A.hp>B.hp?'p':'e';return{winner,events,pMax:A.max,eMax:B.max,turns:turn,pLeft:A.hp,eLeft:B.hp}}
function tick(a,side,events,t,A,B){let d=0;if(a.status.burn>0){d+=Math.max(2,Math.round(a.max*.035));a.status.burn--}if(a.status.poison>0){d+=Math.max(2,Math.round(a.max*.025));a.status.poison--}if(d){a.hp=Math.max(0,a.hp-d);events.push(event(t,`${a.m.name} は状態異常で ${d} ダメージ。`,A,B,'status',side))}}
function resolve(a,b,act,r,t,events,A,B,side){a.cool=Math.max(0,a.cool-1);if(act==='guard'){a.guard=.5+Math.min(.18,a.s.def/600);events.push(event(t,`${a.m.name} は防御態勢。`,A,B,'guard'));return}if(act==='heal'){const sk=a.m.skills.find(x=>x.kind==='heal');const heal=Math.round(a.max*(.18+a.s.mag/600));a.hp=Math.min(a.max,a.hp+heal);a.cool=2;events.push(event(t,`${a.m.name} の「${sk?.name||'リペア'}」！ HPを${heal}回復。`,A,B,'heal'));return}const sk=act==='skill'?a.m.skills[0]:null;if(act==='skill')a.cool=2;const magic=sk&&['magic','multi'].includes(sk.kind),scale=sk?.scale||1,off=magic?a.s.mag*.92+a.s.atk*.25:a.s.atk,def=magic?b.s.mag*.28+b.s.def*.38:b.s.def;let dmg=Math.round((13+off*.72-def*.34)*scale*attrFactor(a.m.attr,b.m.attr)*(.87+r()*.28));if(r()<clamp((b.s.spd-a.s.spd)*.003+.04,.02,.22)){events.push(event(t,`${b.m.name} は回避した！`,A,B,'dodge'));b.guard=0;return}if(r()<.08+a.s.spd/900)dmg=Math.round(dmg*1.55);if(b.status.barrier>0){dmg=Math.round(dmg*.72);b.status.barrier--}if(b.guard){dmg=Math.round(dmg*(1-b.guard));b.guard=0}dmg=Math.max(3,dmg);b.hp=Math.max(0,b.hp-dmg);if(sk?.status&&r()<.42){if(sk.status==='burn')b.status.burn=3;if(sk.status==='poison')b.status.poison=4;if(sk.status==='stun')b.status.stun=1;if(sk.status==='barrier')a.status.barrier=2}events.push(event(t,`${a.m.name} の${sk?'「'+sk.name+'」':'攻撃'}！ ${b.m.name} に ${dmg} ダメージ。`,A,B,sk?'skill':'hit',side==='p'?'e':'p'))}
function event(turn,text,A,B,kind='',hitSide=null){return{turn,text,pHp:A?.hp??0,eHp:B?.hp??0,kind,hitSide}}
async function showBattle(p,e,opt={}){$('#battleModal').classList.remove('hidden');renderGrid($('#pCanvas'),p.grid);renderGrid($('#eCanvas'),e.grid);$('#pName').textContent=p.name;$('#eName').textContent=e.name;$('#battleLog').innerHTML='';$('#battleResult').innerHTML='';$('#nextBattle').classList.add('hidden');const res=simulate(p,e,opt.seed||'battle-'+Date.now());state.lastReplay={p:pack(p),e:pack(e),res};updateHp(res.pMax,res.pMax,res.eMax,res.eMax);const delay=state.settings.speed>=20?0:Math.round(260/state.settings.speed);for(const ev of res.events){$('#turnLabel').textContent='TURN '+String(ev.turn).padStart(2,'0');const q=document.createElement('p');q.className=ev.kind;q.textContent=ev.text;$('#battleLog').appendChild(q);$('#battleLog').scrollTop=$('#battleLog').scrollHeight;updateHp(ev.pHp,res.pMax,ev.eHp,res.eMax);$('#reasonPanel').textContent=reasonText(ev,p,e);if(state.settings.motion&&ev.hitSide){const c=ev.hitSide==='p'?$('#pCanvas'):$('#eCanvas');c.animate([{transform:'translateX(0)'},{transform:'translateX(7px)'},{transform:'translateX(0)'}],{duration:120})}if(delay)await sleep(delay)}const won=res.winner==='p';$('#battleResult').innerHTML=`<h3 class="${won?'win-text':'lose-text'}">${won?'VICTORY':'DEFEAT'}</h3><div>${won?esc(p.name):esc(e.name)} · ${res.turns} TURN</div>`;if(opt.rated){applyRating(won,p,e);rewardMonster(p,won);$('#nextBattle').classList.remove('hidden')}buzz(won?45:90);return res}
function updateHp(p,pm,e,em){$('#pHp').style.width=clamp(p/pm*100,0,100)+'%';$('#eHp').style.width=clamp(e/em*100,0,100)+'%';$('#pHpText').textContent=Math.max(0,p)+'/'+pm;$('#eHpText').textContent=Math.max(0,e)+'/'+em}
function reasonText(ev,p,e){if(ev.kind==='guard')return'AI判断: 被ダメージ期待値が高いため防御';if(ev.kind==='skill')return'AI判断: スキル期待値が通常攻撃を上回った';if(ev.kind==='heal')return'AI判断: HP危険域のため回復';if(ev.kind==='dodge')return'速度差による回避判定';return`相性 ${ATTR[p.attr]}→${ATTR[e.attr]} / POWER ${p.power}:${e.power}`}
function applyRating(won,p,e){const ex=1/(1+Math.pow(10,(e.power-p.power)/38)),d=Math.round(25*((won?1:0)-ex));state.profile.rating=clamp(state.profile.rating+d,100,9999);won?(state.profile.wins++,state.profile.streak++):(state.profile.losses++,state.profile.streak=0);state.profile.coins+=won?12:4;state.profile.xp+=won?20:8;while(state.profile.xp>=state.profile.level*100){state.profile.xp-=state.profile.level*100;state.profile.level++;unlock('level5',state.profile.level>=5)}if(state.profile.streak>=5)unlock('streak5');save();renderProfile();renderRanking()}
function rewardMonster(m,won){const idx=state.collection.findIndex(x=>x.id===m.id);if(idx<0)return;const c=state.collection[idx];c.xp=(c.xp||0)+(won?18:6);if(won)c.wins=(c.wins||0)+1;while(c.xp>=c.level*55&&c.level<20){c.xp-=c.level*55;c.level++;c.power+=1}state.last=revive(c);save()}
function renderCollection(){const e=$('#collectionGrid');$('#collectionCount').textContent=state.collection.length;if(!state.collection.length){e.innerHTML='<div class="empty-state">まだモンスターがいません。</div>';return}e.innerHTML='';[...state.collection].reverse().forEach(m=>{const d=document.createElement('article');d.className='monster-card';d.innerHTML=`<canvas width="192" height="192"></canvas><h3>${esc(m.name)}</h3><p>LV${m.level||1} · ${ATTR[m.attr]} · PWR ${m.power}</p><div class="xpbar"><i style="width:${Math.min(100,((m.xp||0)/((m.level||1)*55))*100)}%"></i></div><button class="small-btn select-monster">選択</button>`;d.querySelector('.select-monster').onclick=()=>{state.last=revive(m);toast(m.name+'を選択')};e.appendChild(d);renderGrid(d.querySelector('canvas'),m.grid)})}
function bindModes(){$('#tournamentStart').onclick=startTournament;$('#towerStart').onclick=startTower;$('#teamAuto').onclick=autoTeam;$('#teamBattle').onclick=teamBattle;$('#makeCode').onclick=exportMonster;$('#loadCode').onclick=importMonster;$('#dailyFight').onclick=dailyFight;$('#runSim').onclick=runSimulation}
function startTournament(){let pool=[...state.collection].slice(-4).map(revive);while(pool.length<8)pool.push(genEnemy('cup-'+Date.now()+'-'+pool.length,pool.length/10));const rounds=[];let cur=pool;while(cur.length>1){const ms=[],next=[];for(let i=0;i<cur.length;i+=2){const a=cur[i],b=cur[i+1],r=simulate(a,b,'cup-'+signature(a.grid)+signature(b.grid)),w=r.winner==='p'?a:b;ms.push({a,b,w});next.push(w)}rounds.push(ms);cur=next}const b=$('#bracket');b.innerHTML='';rounds.forEach((r,i)=>{const c=document.createElement('div');c.className='bracket-col';c.innerHTML=`<h3>${i===rounds.length-1?'FINAL':'ROUND '+(i+1)}</h3>`;r.forEach(m=>c.innerHTML+=`<div class="bracket-match"><b class="${m.w===m.a?'win':''}">${esc(m.a.name)}</b><b class="${m.w===m.b?'win':''}">${esc(m.b.name)}</b></div>`);b.appendChild(c)});unlock('cup')}
async function startTower(){if(!state.last){toast('図鑑からモンスターを選択');return}let floor=1;$('#towerStatus').innerHTML='';while(floor<=30){const boss=floor%5===0,e=genEnemy('tower-'+floor,floor/5,boss),r=simulate(state.last,e,'tower-seed-'+floor);$('#towerStatus').innerHTML+=`<div>${floor}F ${boss?'BOSS ':''}${esc(e.name)} → <b class="${r.winner==='p'?'win-text':'lose-text'}">${r.winner==='p'?'WIN':'LOSE'}</b></div>`;if(r.winner!=='p')break;floor++;state.profile.bestTower=Math.max(state.profile.bestTower,floor-1);state.profile.coins+=boss?30:8;await sleep(40)}if(state.profile.bestTower>=10)unlock('tower10');save();renderProfile()}
function autoTeam(){state.team=[...state.collection].slice(-6).map(revive);renderTeam()}
function renderTeam(){const e=$('#teamSlots');if(!e)return;e.innerHTML='';for(let i=0;i<6;i++){const m=state.team[i],d=document.createElement('div');d.className='team-slot';d.innerHTML=m?`<b>${i+1}. ${esc(m.name)}</b><small>${ATTR[m.attr]} P${m.power}</small>`:`<b>${i+1}. EMPTY</b>`;e.appendChild(d)}}
function teamBattle(){if(state.team.length<1){autoTeam();if(!state.team.length){toast('図鑑にモンスターが必要');return}}const enemy=Array.from({length:6},(_,i)=>genEnemy('team-'+Date.now()+'-'+i,.5+i*.1));let a=0,b=0,log=[];while(a<state.team.length&&b<enemy.length){const r=simulate(state.team[a],enemy[b],'team-match-'+a+'-'+b);if(r.winner==='p'){log.push(`${state.team[a].name} > ${enemy[b].name}`);b++}else{log.push(`${state.team[a].name} < ${enemy[b].name}`);a++}}const won=b>=enemy.length;$('#teamResult').innerHTML=log.map(x=>`<div>${esc(x)}</div>`).join('')+`<h3 class="${won?'win-text':'lose-text'}">${won?'TEAM VICTORY':'TEAM DEFEAT'}</h3>`;if(won)unlock('teamwin')}
function exportMonster(){if(!state.last){toast('先にモンスターを選択');return}const raw=JSON.stringify(pack(state.last)),code='PFA2-'+btoa(unescape(encodeURIComponent(raw))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');$('#exportCode').value=code;navigator.clipboard?.writeText(code).catch(()=>{});unlock('export')}
function importMonster(){try{let c=$('#importCode').value.trim();if(!c.startsWith('PFA2-'))throw 0;c=c.slice(5).replace(/-/g,'+').replace(/_/g,'/');while(c.length%4)c+='=';const m=JSON.parse(decodeURIComponent(escape(atob(c))));if(!Array.isArray(m.grid)||!m.stats)throw 0;m.id='import-'+Date.now();addMonster(revive(m));state.last=revive(m);renderCollection();toast('召喚成功');unlock('import')}catch{toast('コードが壊れています')}}
function renderDaily(){const d=new Date(),key=`${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`,e=genEnemy('daily-'+key,1.2);state.dailyEnemy=e;$('#dailyDate').textContent=key;$('#dailyName').textContent=e.name;renderGrid($('#dailyEnemy'),e.grid)}
async function dailyFight(){if(!state.last){toast('モンスターを選択');return}const r=simulate(state.last,state.dailyEnemy,'daily-battle-'+new Date().toDateString());$('#dailyResult').innerHTML=`<h3 class="${r.winner==='p'?'win-text':'lose-text'}">${r.winner==='p'?'DAILY CLEAR':'FAILED'}</h3><p>${r.turns} TURN</p>`;if(r.winner==='p'){state.profile.coins+=25;unlock('daily');save()}}
function runSimulation(){if(!state.last){toast('モンスターを選択');return}let w=0,t=0;for(let i=0;i<100;i++){const r=simulate(state.last,state.enemy,'sim-'+i);if(r.winner==='p')w++;t+=r.turns}$('#simResult').innerHTML=`<div class="sim-big">${w}%</div><p>勝率 / 平均 ${(t/100).toFixed(1)}ターン</p><p>${w>=70?'有利':w<=40?'不利':'互角'} 判定</p>`;unlock('sim')}
function renderRanking(){const rs=[['BYTEFOX',1460,32],['NEON',1388,24],['KAMI-9',1335,21],['MOKA',1260,17],['R0NIN',1192,13],['PIXELCAT',1134,11]].map(x=>({name:x[0],rating:x[1],wins:x[2]}));rs.push({name:state.profile.name,rating:state.profile.rating,wins:state.profile.wins,you:true});rs.sort((a,b)=>b.rating-a.rating);$('#rankingList').innerHTML=rs.map((r,i)=>`<div class="rank-row ${r.you?'you':''}"><span>#${i+1}</span><b>${esc(r.name)}${r.you?' (YOU)':''}</b><strong>${r.rating}</strong><small>${r.wins}W</small></div>`).join('')}
const ACH={collector:['最初の登録','モンスターを図鑑に登録'],streak5:['5連勝','5連勝する'],level5:['トレーナーLV5','プレイヤーレベル5'],cup:['大会開催','トーナメントを開催'],tower10:['10F到達','タワー10階到達'],teamwin:['連携勝利','6体チーム戦に勝利'],export:['コード職人','モンスターコードを生成'],import:['召喚士','コードから召喚'],daily:['今日の勝者','デイリーをクリア'],sim:['研究者','100戦シミュレーション']};
function unlock(k,cond=true){if(cond&&!state.ach[k]){state.ach[k]=Date.now();save();toast('実績解除: '+ACH[k][0])}}
function renderAchievements(){const g=$('#achievementGrid');g.innerHTML=Object.entries(ACH).map(([k,v])=>`<div class="achievement ${state.ach[k]?'done':''}"><b>${state.ach[k]?'★':'◇'} ${v[0]}</b><small>${v[1]}</small></div>`).join('')}
function bindOnline(){$('#createRoom').onclick=hostRoom;$('#joinRoom').onclick=joinRoom;$('#sendReady').onclick=sendOnline}
function room(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',u=new Uint32Array(6);crypto.getRandomValues(u);return[...u].map(n=>chars[n%chars.length]).join('')}
function hostRoom(){if(typeof Peer==='undefined'){toast('通信ライブラリ未読込');return}cleanupPeer();state.isHost=true;state.room=room();state.peer=new Peer('pfa2-'+state.room.toLowerCase());state.peer.on('open',()=>{$('#roomCode').textContent=state.room;$('#roomBox').classList.remove('hidden');$('#onlineCard').classList.remove('hidden');$('#netLamp').textContent='ROOM '+state.room;$('#netLamp').classList.add('good')});state.peer.on('connection',setupConn);peerErr()}
function joinRoom(){if(typeof Peer==='undefined'){toast('通信ライブラリ未読込');return}const c=$('#joinCode').value.trim().toUpperCase();if(c.length!==6){toast('6文字コード');return}cleanupPeer();state.isHost=false;state.room=c;state.peer=new Peer();state.peer.on('open',()=>setupConn(state.peer.connect('pfa2-'+c.toLowerCase(),{reliable:true})));peerErr()}
function peerErr(){state.peer.on('error',()=>{$('#netLamp').textContent='ERROR';toast('通信エラー')})}
function setupConn(c){if(state.conn?.open){c.close();return}state.conn=c;c.on('open',()=>{$('#onlineCard').classList.remove('hidden');$('#netLamp').textContent='ONLINE';$('#netLamp').classList.add('good');c.send({t:'hello',name:state.profile.name,rating:state.profile.rating})});c.on('data',netData)}
function netData(d){if(d.t==='hello'){$('#onlineRival').textContent=d.name;$('#onlineRivalState').textContent='RATING '+d.rating;state.conn.send({t:'ack',name:state.profile.name,rating:state.profile.rating})}if(d.t==='ack'){$('#onlineRival').textContent=d.name;$('#onlineRivalState').textContent='RATING '+d.rating}if(d.t==='ready'){state.remote=revive(d.m);$('#onlineRivalState').textContent='READY';maybeOnline()}if(d.t==='result'&&!state.isHost){const won=!d.hostWon;$('#onlineResult').innerHTML=`<h3 class="${won?'win-text':'lose-text'}">${won?'YOU WIN':'YOU LOSE'}</h3>`;onlineRate(won)}}
function sendOnline(){if(!state.conn?.open){toast('未接続');return}if(!state.last)state.last=genEnemy('online-auto-'+Date.now(),.2);state.ready=true;state.conn.send({t:'ready',m:pack(state.last)});$('#onlineMeState').textContent='READY';maybeOnline()}
function maybeOnline(){if(!state.isHost||!state.ready||!state.remote)return;const r=simulate(state.last,state.remote,'online-'+state.room+signature(state.last.grid)+signature(state.remote.grid)),won=r.winner==='p';$('#onlineResult').innerHTML=`<h3 class="${won?'win-text':'lose-text'}">${won?'YOU WIN':'YOU LOSE'}</h3>`;state.conn.send({t:'result',hostWon:won});onlineRate(won)}
function onlineRate(w){state.profile.rating=clamp(state.profile.rating+(w?18:-14),100,9999);w?state.profile.wins++:state.profile.losses++;save();renderProfile()}
function cleanupPeer(){try{state.conn?.close();state.peer?.destroy()}catch{}state.conn=null;state.peer=null;state.ready=false;state.remote=null}
function bindSettings(){$('#speedSel').value=state.settings.speed;$('#vibSet').checked=state.settings.vibration;$('#motionSet').checked=state.settings.motion;$('#speedSel').onchange=e=>{state.settings.speed=+e.target.value;save()};$('#vibSet').onchange=e=>{state.settings.vibration=e.target.checked;save()};$('#motionSet').onchange=e=>{state.settings.motion=e.target.checked;save()};$('#resetData').onclick=()=>{if(confirm('すべて削除しますか？')){['pf2_profile','pf2_collection','pf2_ach','pf2_settings'].forEach(k=>localStorage.removeItem(k));location.reload()}}}
function titleSprites(){renderGrid($('#titleA'),genEnemy('title-a',.2).grid,'transparent');renderGrid($('#titleB'),genEnemy('title-b',.2).grid,'transparent')}
init();
})();
