(() => {
'use strict';
const c=document.getElementById('sim'),ctx=c.getContext('2d');
const g=document.getElementById('graph'),gctx=g.getContext('2d');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const TAU=Math.PI*2, clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const wrapAngle=a=>Math.atan2(Math.sin(a),Math.cos(a));
const angleTo=(a,b)=>Math.atan2(b.y-a.y,b.x-a.x);
const dist=(a,b)=>Math.hypot(b.x-a.x,b.y-a.y);
const vecFrom=(ang,len)=>({x:Math.cos(ang)*len,y:Math.sin(ang)*len});
const WORLD={w:3400,h:2200};
const TARGET_PRESETS={
  fighter:{name:'FAST JET',size:8,accel:42,drag:.0022},
  bomber:{name:'HEAVY AIRCRAFT',size:13,accel:24,drag:.0028},
  drone:{name:'LIGHT DRONE',size:6,accel:54,drag:.0019},
  transport:{name:'TRANSPORT',size:14,accel:20,drag:.003},
  balloon:{name:'SLOW PLATFORM',size:11,accel:7,drag:.0045}
};
const state={paused:false,timeScale:1,simTime:0,player:null,targets:[],trackers:[],selectedTarget:0,waypoint:{x:2400,y:1100},trails:true,prediction:true,vectors:false,telemetry:[],graph:[],stick:{x:0,y:0,active:false},scenario:'headon'};
function input(id){return document.getElementById(id)}
function num(id){return +input(id).value}
function init(){bindUI();resize();resetScenario('headon');requestAnimationFrame(loop)}
function makePlayer(){return{x:700,y:1100,heading:0,speed:88,alt:450,verticalSpeed:0,fuel:num('airFuel'),maxFuel:num('airFuel'),throttle:num('throttle')/100,turnPower:num('airTurn')/100,trail:[],ap:'manual',apHeading:num('apHeading')*Math.PI/180,apAlt:num('apAltitude'),size:11}}
function makeTarget(i,type=input('targetType').value){const p=TARGET_PRESETS[type],ang=Math.PI+(i-.5)*.08;return{id:'T'+(i+1),type,name:p.name,x:2450+i*70,y:850+i*110,heading:ang,speed:num('targetSpeed')*(.92+i*.025),desiredSpeed:num('targetSpeed'),alt:num('targetAlt')+i*15,turnPower:num('targetTurn')/100,behavior:input('targetBehavior').value,size:p.size,accel:p.accel,drag:p.drag,phase:i*1.7,trail:[],alive:true,waypointIndex:i%4}}
function resetScenario(kind=state.scenario){state.scenario=kind;state.simTime=0;state.player=makePlayer();state.targets=[];state.trackers=[];const count=kind==='swarm'?Math.max(4,num('targetCount')):num('targetCount');for(let i=0;i<count;i++)state.targets.push(makeTarget(i));applyScenario(kind);state.selectedTarget=0;state.telemetry=[];state.graph=[];renderTelemetry()}
function applyScenario(k){const p=state.player;if(k==='headon'){p.x=550;p.y=1100;p.heading=0;state.targets.forEach((t,i)=>{t.x=2700;t.y=1000+i*80;t.heading=Math.PI;t.behavior='straight'})}if(k==='cross'){p.x=650;p.y=1650;p.heading=-.2;state.targets.forEach((t,i)=>{t.x=1700+i*80;t.y=280;t.heading=Math.PI/2;t.behavior='cross'})}if(k==='chase'){p.x=650;p.y=1100;p.heading=0;state.targets.forEach((t,i)=>{t.x=1950+i*90;t.y=1050+i*65;t.heading=.05;t.behavior='zigzag'})}if(k==='orbit'){p.x=700;p.y=1500;p.heading=-.4;state.targets.forEach((t,i)=>{t.x=2200+i*65;t.y=1100;t.behavior='orbit';t.heading=Math.PI/2})}if(k==='evasive'){p.x=650;p.y=1500;p.heading=-.3;state.targets.forEach((t,i)=>{t.x=2200+i*80;t.y=900+i*60;t.behavior='evade'})}if(k==='swarm'){p.x=700;p.y=1100;p.heading=0;state.targets.forEach((t,i)=>{const a=i/Math.max(1,state.targets.length)*TAU;t.x=2200+Math.cos(a)*500;t.y=1100+Math.sin(a)*430;t.heading=a+Math.PI/2;t.behavior=i%2?'orbit':'zigzag'})}}
function bindUI(){
  window.addEventListener('resize',resize);$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tabpane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.add('active')});
  $$('[data-scenario]').forEach(b=>b.onclick=()=>resetScenario(b.dataset.scenario));
  $('#pauseBtn').onclick=()=>{state.paused=!state.paused;$('#pauseBtn').textContent=state.paused?'RESUME':'PAUSE'};$('#resetBtn').onclick=()=>resetScenario();
  $('#timeScale').onchange=e=>state.timeScale=+e.target.value;$('#showTrails').onchange=e=>state.trails=e.target.checked;$('#showPrediction').onchange=e=>state.prediction=e.target.checked;$('#showVectors').onchange=e=>state.vectors=e.target.checked;
  linkRange('apHeading','headingOut',v=>`${String(Math.round(v)).padStart(3,'0')}°`,v=>{state.player&&(state.player.apHeading=v*Math.PI/180)});linkRange('apAltitude','altOut',v=>Math.round(v),v=>{state.player&&(state.player.apAlt=v)});linkRange('throttle','throttleOut',v=>Math.round(v)+'%',v=>{state.player&&(state.player.throttle=v/100)});linkRange('airTurn','turnOut',v=>Math.round(v),v=>{state.player&&(state.player.turnPower=v/100)});linkRange('airFuel','airFuelOut',v=>Math.round(v)+'%');
  linkRange('targetSpeed','targetSpeedOut',v=>Math.round(v),v=>state.targets.forEach(t=>t.desiredSpeed=v));linkRange('targetTurn','targetTurnOut',v=>Math.round(v),v=>state.targets.forEach(t=>t.turnPower=v/100));linkRange('targetAlt','targetAltOut',v=>Math.round(v),v=>state.targets.forEach(t=>t.alt=v));linkRange('targetCount','targetCountOut',v=>Math.round(v));
  linkRange('missileSpeed','missileSpeedOut',v=>Math.round(v));linkRange('missileFuel','missileFuelOut',v=>(+v).toFixed(1));linkRange('missileTurn','missileTurnOut',v=>Math.round(v));linkRange('prediction','predictionOut',v=>Math.round(v)+'%');linkRange('trackerThrottle','trackerThrottleOut',v=>Math.round(v)+'%');
  $('#apMode').onchange=e=>{if(state.player)state.player.ap=e.target.value};$('#applyTargets').onclick=()=>{state.targets=[];for(let i=0;i<num('targetCount');i++)state.targets.push(makeTarget(i));state.trackers=[];state.selectedTarget=0;applyScenario(state.scenario)};
  $('#targetType').onchange=()=>{};$('#targetBehavior').onchange=e=>state.targets.forEach(t=>t.behavior=e.target.value);$('#launchBtn').onclick=launchTracker;$('#mobileLaunch').onclick=launchTracker;$('#mobileAuto').onclick=()=>{const modes=['manual','heading','altitude','waypoint'];const i=(modes.indexOf(state.player.ap)+1)%modes.length;state.player.ap=modes[i];$('#apMode').value=state.player.ap};$('#setWaypoint').onclick=()=>{const cam=camera();state.waypoint={x:cam.x,y:cam.y};state.player.ap='waypoint';$('#apMode').value='waypoint'};$('#clearTelemetry').onclick=()=>{state.telemetry=[];state.graph=[];renderTelemetry()};
  c.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;const p=worldPoint(e);const hit=state.targets.filter(t=>t.alive).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(hit&&dist(hit,p)<90)state.selectedTarget=state.targets.indexOf(hit);else state.waypoint=p});
  bindStick();window.addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key))state.stick.x=-1;if(['ArrowRight','d','D'].includes(e.key))state.stick.x=1;if(['ArrowUp','w','W'].includes(e.key))state.stick.y=-1;if(['ArrowDown','s','S'].includes(e.key))state.stick.y=1;if(e.code==='Space'){e.preventDefault();launchTracker()}});window.addEventListener('keyup',e=>{if(['ArrowLeft','ArrowRight','a','A','d','D'].includes(e.key))state.stick.x=0;if(['ArrowUp','ArrowDown','w','W','s','S'].includes(e.key))state.stick.y=0});
}
function linkRange(id,out,format,onchange){const e=input(id),o=input(out);const run=()=>{o.textContent=format(e.value);onchange?.(+e.value)};e.addEventListener('input',run);run()}
function bindStick(){const z=$('#stickZone'),k=$('#stickKnob');let pid=null;const set=e=>{const r=z.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.32,len=Math.hypot(dx,dy)||1,m=Math.min(max,len),nx=dx/len*m,ny=dy/len*m;state.stick.x=nx/max;state.stick.y=ny/max;k.style.transform=`translate(${nx}px,${ny}px)`};z.addEventListener('pointerdown',e=>{pid=e.pointerId;z.setPointerCapture(pid);state.stick.active=true;set(e)});z.addEventListener('pointermove',e=>{if(e.pointerId===pid)set(e)});const end=e=>{if(e.pointerId!==pid)return;pid=null;state.stick.active=false;state.stick.x=0;state.stick.y=0;k.style.transform='translate(0,0)'};z.addEventListener('pointerup',end);z.addEventListener('pointercancel',end)}
function launchTracker(){const t=state.targets[state.selectedTarget];if(!t||!t.alive){toast('標的がありません');return}const p=state.player,dir=p.heading;state.trackers.push({x:p.x+Math.cos(dir)*20,y:p.y+Math.sin(dir)*20,heading:dir,speed:Math.max(p.speed+35,num('missileSpeed')*.58),targetId:t.id,fuel:num('missileFuel'),maxFuel:num('missileFuel'),turn:num('missileTurn')/100,desiredSpeed:num('missileSpeed'),throttle:num('trackerThrottle')/100,trail:[],alive:true,age:0,predict:null,lastTurn:0});log(`TRACKER → ${t.id}`)}
function update(dt){state.simTime+=dt;updatePlayer(dt);state.targets.forEach(t=>updateTarget(t,dt));state.trackers.forEach(m=>updateTracker(m,dt));state.trackers=state.trackers.filter(m=>m.alive&&m.age<60);state.targets=state.targets.filter(t=>t.alive);if(state.selectedTarget>=state.targets.length)state.selectedTarget=Math.max(0,state.targets.length-1);updateHUD();sampleGraph()}
function updatePlayer(dt){const p=state.player;if(!p)return;const manualTurn=state.stick.x;let turnCmd=manualTurn,verticalCmd=-state.stick.y;
  if(p.ap!=='manual'){
    let desired=p.heading;
    if(p.ap==='heading'||p.ap==='altitude')desired=p.apHeading;
    if(p.ap==='waypoint')desired=angleTo(p,state.waypoint);
    if(p.ap==='orbit'){const center={x:WORLD.w*.55,y:WORLD.h*.5},radial=angleTo(center,p);desired=radial+Math.PI/2}
    turnCmd=clamp(wrapAngle(desired-p.heading)*1.8,-1,1);
    if(['altitude','waypoint','orbit'].includes(p.ap))verticalCmd=clamp((p.apAlt-p.alt)/180,-1,1);
  }
  const turnRate=(.38+.72*p.turnPower)*(70/(40+p.speed));p.heading=wrapAngle(p.heading+turnCmd*turnRate*dt*3.2);
  p.verticalSpeed=lerp(p.verticalSpeed,verticalCmd*95,1-Math.exp(-dt*1.8));p.alt=clamp(p.alt+p.verticalSpeed*dt,20,990);
  const fuelRatio=p.maxFuel?clamp(p.fuel/p.maxFuel,0,1):0;const thrust=p.fuel>0?p.throttle*52:0;const drag=.0025*p.speed*p.speed;const turnLoss=Math.abs(turnCmd)*p.speed*.045;p.speed=clamp(p.speed+(thrust-drag-turnLoss)*dt,25,165);
  if(p.fuel>0){const burn=(.13+.62*p.throttle*p.throttle+Math.abs(turnCmd)*.08)*dt;p.fuel=Math.max(0,p.fuel-burn)}
  p.x+=Math.cos(p.heading)*p.speed*dt;p.y+=Math.sin(p.heading)*p.speed*dt;wrapWorld(p);trail(p,70);p.fuelRatio=fuelRatio}
function updateTarget(t,dt){let desired=t.heading;const speedBase=t.desiredSpeed;
  if(t.behavior==='orbit'){const center={x:WORLD.w*.67,y:WORLD.h*.5};desired=angleTo(center,t)+Math.PI/2}
  else if(t.behavior==='zigzag'){desired=t.heading+Math.sin(state.simTime*.9+t.phase)*.8}
  else if(t.behavior==='evade'){const threat=nearestTracker(t);if(threat&&dist(t,threat)<520){const away=angleTo(threat,t);desired=away+Math.sin(state.simTime*1.5+t.phase)*.75}else desired=t.heading+Math.sin(state.simTime*.55+t.phase)*.4}
  else if(t.behavior==='waypoints'){const pts=[{x:2600,y:350},{x:3000,y:1750},{x:1500,y:1850},{x:1350,y:420}],wp=pts[t.waypointIndex%pts.length];desired=angleTo(t,wp);if(dist(t,wp)<140)t.waypointIndex++}
  else if(t.behavior==='cross'){desired=Math.PI/2+.08*Math.sin(state.simTime*.4+t.phase)}
  const err=wrapAngle(desired-t.heading),turnRate=(.22+.78*t.turnPower)*(95/(55+t.speed));t.heading=wrapAngle(t.heading+clamp(err,-1,1)*turnRate*dt*2.5);
  const accel=TARGET_PRESETS[t.type].accel,drag=TARGET_PRESETS[t.type].drag*t.speed*t.speed;t.speed=clamp(t.speed+(accel*.18-drag)*dt,10,speedBase*1.14);t.x+=Math.cos(t.heading)*t.speed*dt;t.y+=Math.sin(t.heading)*t.speed*dt;wrapWorld(t);trail(t,55)}
function updateTracker(m,dt){m.age+=dt;const t=state.targets.find(x=>x.id===m.targetId&&x.alive);if(!t){m.alive=false;return}const range=dist(m,t);const predictionStrength=num('prediction')/100;const relSpeed=Math.max(40,m.speed+t.speed*.25);const look=clamp(range/relSpeed,0,.95+predictionStrength*2.2);const tv=vecFrom(t.heading,t.speed);const rawPred={x:t.x+tv.x*look*predictionStrength,y:t.y+tv.y*look*predictionStrength};const direct={x:t.x,y:t.y};m.predict={x:lerp(direct.x,rawPred.x,predictionStrength),y:lerp(direct.y,rawPred.y,predictionStrength)};
  const desired=angleTo(m,m.predict),err=wrapAngle(desired-m.heading),maxTurn=(.55+2.7*m.turn)*(110/(60+m.speed));const applied=clamp(err,-maxTurn*dt,maxTurn*dt);m.heading=wrapAngle(m.heading+applied);m.lastTurn=Math.abs(applied)/(dt||1);
  const hasFuel=m.fuel>0,thrust=hasFuel?m.throttle*95:0,drag=.00165*m.speed*m.speed;const steeringLoss=m.speed*m.lastTurn*.024;m.speed=clamp(m.speed+(thrust-drag-steeringLoss)*dt,18,m.desiredSpeed*1.08);
  if(hasFuel){let burn=(.35+1.15*m.throttle*m.throttle)*dt;if($('#steeringFuel').checked)burn+=m.lastTurn*.12*dt;m.fuel=Math.max(0,m.fuel-burn)}
  m.x+=Math.cos(m.heading)*m.speed*dt;m.y+=Math.sin(m.heading)*m.speed*dt;wrapWorld(m);trail(m,85);
  if(range<14+t.size){t.alive=false;m.alive=false;log(`${t.id} TRACK COMPLETE / ${m.age.toFixed(1)}s / FUEL ${m.fuel.toFixed(1)}`);flash()}
  else if(m.age>8&&m.fuel<=0&&m.speed<35){m.alive=false;log(`${m.targetId} TRACK LOST / FUEL DEPLETED`)}
}
function nearestTracker(t){let best=null,d=Infinity;for(const m of state.trackers){if(!m.alive)continue;const x=dist(t,m);if(x<d){d=x;best=m}}return best}
function wrapWorld(o){if(o.x<0)o.x+=WORLD.w;if(o.x>WORLD.w)o.x-=WORLD.w;if(o.y<0)o.y+=WORLD.h;if(o.y>WORLD.h)o.y-=WORLD.h}
function trail(o,max){o.trail.push({x:o.x,y:o.y});if(o.trail.length>max)o.trail.shift()}
function camera(){return{x:state.player?.x||WORLD.w/2,y:state.player?.y||WORLD.h/2}}
function resize(){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.max(640,Math.floor(r.width*d));c.height=Math.max(400,Math.floor(r.height*d));ctx.setTransform(1,0,0,1,0,0);g.width=Math.max(320,Math.floor(g.getBoundingClientRect().width*d));g.height=Math.floor(130*d)}
function worldPoint(e){const r=c.getBoundingClientRect(),cam=camera(),scale=scaleView()/(devicePixelRatio||1);return{x:cam.x+(e.clientX-r.left-r.width/2)/scale,y:cam.y+(e.clientY-r.top-r.height/2)/scale}}
function scaleView(){return Math.min(c.clientWidth/1500,c.clientHeight/900)*(devicePixelRatio||1)}
function draw(){const w=c.width,h=c.height;ctx.clearRect(0,0,w,h);const cam=camera(),s=scaleView();ctx.save();ctx.translate(w/2-cam.x*s,h/2-cam.y*s);ctx.scale(s,s);drawGrid(cam,s,w,h);if(state.trails){drawTrails(state.player,'#45e8ff55');state.targets.forEach(t=>drawTrails(t,'#ff586f44'));state.trackers.forEach(m=>drawTrails(m,'#ffcf5755'))}drawWaypoint();state.targets.forEach((t,i)=>drawTarget(t,i===state.selectedTarget));state.trackers.forEach(drawTracker);drawPlayer(state.player);ctx.restore();drawEdges();drawGraph()}
function drawGrid(cam,s,w,h){const step=200;ctx.strokeStyle='#17304a55';ctx.lineWidth=1/s;const minX=Math.floor((cam.x-w/(2*s))/step)*step,maxX=cam.x+w/(2*s),minY=Math.floor((cam.y-h/(2*s))/step)*step,maxY=cam.y+h/(2*s);for(let x=minX;x<maxX;x+=step){ctx.beginPath();ctx.moveTo(x,minY);ctx.lineTo(x,maxY);ctx.stroke()}for(let y=minY;y<maxY;y+=step){ctx.beginPath();ctx.moveTo(minX,y);ctx.lineTo(maxX,y);ctx.stroke()}}
function drawTrails(o,color){if(!o||o.trail.length<2)return;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();o.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}
function drawPlayer(p){if(!p)return;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.heading);ctx.fillStyle='#45e8ff';ctx.beginPath();ctx.moveTo(15,0);ctx.lineTo(-10,-7);ctx.lineTo(-5,0);ctx.lineTo(-10,7);ctx.closePath();ctx.fill();ctx.strokeStyle='#c9f8ff';ctx.stroke();ctx.restore();if(state.vectors)drawVector(p,'#45e8ff')}
function drawTarget(t,sel){ctx.save();ctx.translate(t.x,t.y);ctx.rotate(t.heading);ctx.fillStyle=sel?'#ffcf57':'#ff586f';ctx.beginPath();if(t.type==='drone'){ctx.arc(0,0,t.size,0,TAU)}else{ctx.moveTo(t.size+5,0);ctx.lineTo(-t.size,-t.size*.65);ctx.lineTo(-t.size*.45,0);ctx.lineTo(-t.size,t.size*.65);ctx.closePath()}ctx.fill();ctx.restore();if(sel){ctx.strokeStyle='#ffcf57';ctx.lineWidth=1.5;ctx.strokeRect(t.x-24,t.y-24,48,48);ctx.fillStyle='#ffcf57';ctx.font='11px monospace';ctx.fillText(`${t.id} ${Math.round(t.speed)}`,t.x+30,t.y-12)}if(state.vectors)drawVector(t,'#ff586f')}
function drawTracker(m){ctx.save();ctx.translate(m.x,m.y);ctx.rotate(m.heading);ctx.fillStyle=m.fuel>0?'#ffcf57':'#9aa6b6';ctx.beginPath();ctx.moveTo(10,0);ctx.lineTo(-7,-3);ctx.lineTo(-7,3);ctx.closePath();ctx.fill();if(m.fuel>0){ctx.strokeStyle='#ff8a55';ctx.beginPath();ctx.moveTo(-7,0);ctx.lineTo(-15-Math.random()*6,0);ctx.stroke()}ctx.restore();if(state.prediction&&m.predict){ctx.strokeStyle='#ffcf5744';ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(m.x,m.y);ctx.lineTo(m.predict.x,m.predict.y);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#ffcf57aa';ctx.beginPath();ctx.arc(m.predict.x,m.predict.y,6,0,TAU);ctx.stroke()}if(state.vectors)drawVector(m,'#ffcf57')}
function drawVector(o,color){const v=vecFrom(o.heading,o.speed*.6);ctx.strokeStyle=color+'88';ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.lineTo(o.x+v.x,o.y+v.y);ctx.stroke()}
function drawWaypoint(){ctx.strokeStyle='#5bffb066';ctx.lineWidth=1;ctx.beginPath();ctx.arc(state.waypoint.x,state.waypoint.y,18,0,TAU);ctx.stroke();ctx.beginPath();ctx.moveTo(state.waypoint.x-24,state.waypoint.y);ctx.lineTo(state.waypoint.x+24,state.waypoint.y);ctx.moveTo(state.waypoint.x,state.waypoint.y-24);ctx.lineTo(state.waypoint.x,state.waypoint.y+24);ctx.stroke()}
function drawEdges(){const t=state.targets[state.selectedTarget];if(!t)return;const p=screenPos(t);if(p.x>30&&p.x<c.width-30&&p.y>30&&p.y<c.height-30)return;const cx=c.width/2,cy=c.height/2,a=Math.atan2(p.y-cy,p.x-cx),r=Math.min(c.width,c.height)*.42;ctx.save();ctx.translate(cx+Math.cos(a)*r,cy+Math.sin(a)*r);ctx.rotate(a);ctx.fillStyle='#ffcf57';ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-8,-7);ctx.lineTo(-8,7);ctx.closePath();ctx.fill();ctx.restore()}
function screenPos(o){const cam=camera(),s=scaleView();return{x:c.width/2+(o.x-cam.x)*s,y:c.height/2+(o.y-cam.y)*s}}
function updateHUD(){const p=state.player,t=state.targets[state.selectedTarget];$('#hudSpeed').textContent=Math.round(p.speed);$('#hudAlt').textContent=Math.round(p.alt);$('#hudHeading').textContent=String(Math.round((p.heading*180/Math.PI+360)%360)).padStart(3,'0');$('#hudFuel').textContent=(p.fuel/p.maxFuel*100).toFixed(0);$('#hudMode').textContent=p.ap.toUpperCase();$('#hudTarget').textContent=t?t.id:'---';$('#hudRange').textContent=t?Math.round(dist(p,t)):'---';$('#hudTargetSpeed').textContent=t?Math.round(t.speed):'---';$('#hudMissiles').textContent=state.trackers.length;$('#hudTimeScale').textContent=state.timeScale.toFixed(2).replace(/\.00$/,'')+'×';if(Math.floor(state.simTime*4)%2===0)renderTelemetry()}
function renderTelemetry(){const p=state.player,t=state.targets[state.selectedTarget],m=state.trackers.find(x=>x.alive&&t&&x.targetId===t.id);const vals=[['SIM TIME',state.simTime.toFixed(1)+' s'],['AIR FUEL',p?`${p.fuel.toFixed(1)} / ${p.maxFuel}`:'-'],['AIR SPEED',p?Math.round(p.speed):'-'],['AIR ALT',p?Math.round(p.alt):'-'],['TARGET',t?t.id+' '+t.name:'NONE'],['RANGE',t?Math.round(dist(p,t)):'-'],['TRACK FUEL',m?m.fuel.toFixed(1):'-'],['TRACK SPEED',m?Math.round(m.speed):'-'],['LOOK AHEAD',m&&m.predict?Math.round(dist(t,m.predict)):'-'],['TRACK AGE',m?m.age.toFixed(1):'-']];$('#telemetry').innerHTML=vals.map(v=>`<div><small>${v[0]}</small><b>${v[1]}</b></div>`).join('')}
function sampleGraph(){if(Math.floor(state.simTime*10)===Math.floor((state.simTime-state.timeScale/60)*10))return;const t=state.targets[state.selectedTarget],m=state.trackers.find(x=>x.alive&&t&&x.targetId===t.id);state.graph.push({t:state.simTime,range:t?dist(state.player,t):0,fuel:m?m.fuel:0});if(state.graph.length>180)state.graph.shift()}
function drawGraph(){if(!gctx)return;const w=g.width,h=g.height;gctx.clearRect(0,0,w,h);gctx.fillStyle='#050a12';gctx.fillRect(0,0,w,h);if(state.graph.length<2)return;const maxR=Math.max(1,...state.graph.map(x=>x.range));gctx.strokeStyle='#45e8ff';gctx.beginPath();state.graph.forEach((v,i)=>{const x=i/(state.graph.length-1)*w,y=h-10-v.range/maxR*(h-20);i?gctx.lineTo(x,y):gctx.moveTo(x,y)});gctx.stroke();const mf=Math.max(1,num('missileFuel'));gctx.strokeStyle='#ffcf57';gctx.beginPath();state.graph.forEach((v,i)=>{const x=i/(state.graph.length-1)*w,y=h-10-v.fuel/mf*(h-20);i?gctx.lineTo(x,y):gctx.moveTo(x,y)});gctx.stroke();gctx.fillStyle='#71869f';gctx.font=`${10*(devicePixelRatio||1)}px monospace`;gctx.fillText('CYAN: RANGE   AMBER: TRACK FUEL',8,13*(devicePixelRatio||1))}
function log(msg){state.telemetry.push({time:state.simTime,msg});if(state.telemetry.length>20)state.telemetry.shift();$('#notice').textContent=msg;setTimeout(()=>{$('#notice').textContent='SIM UNITS — REAL-WORLD WEAPON DATA IS NOT USED'},1800)}
function flash(){c.classList.remove('flash');void c.offsetWidth;c.classList.add('flash')}
function toast(msg){log(msg)}
let last=performance.now();function loop(now){let dt=Math.min(.04,(now-last)/1000);last=now;if(!state.paused){const steps=Math.max(1,Math.ceil(state.timeScale));const sub=dt*state.timeScale/steps;for(let i=0;i<steps;i++)update(sub)}draw();requestAnimationFrame(loop)}
init();
})();
